-- MySQL Script generated by MySQL Workbench
-- 06/30/18 14:14:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema indbandeirante
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema indbandeirante
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `indbandeirante` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `indbandeirante` ;

-- -----------------------------------------------------
-- Table `indbandeirante`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `indbandeirante`.`user` ;

CREATE TABLE IF NOT EXISTS `indbandeirante`.`user` (
  `us_ukey` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `us_nome` VARCHAR(100) NOT NULL COMMENT '',
  `us_email` VARCHAR(100) NOT NULL COMMENT '',
  `us_sexo` VARCHAR(1) NOT NULL COMMENT '',
  `us_data` DATE NOT NULL COMMENT '',
  `us_time` TIME NOT NULL COMMENT '',
  PRIMARY KEY (`us_ukey`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indbandeirante`.`pass`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `indbandeirante`.`pass` ;

CREATE TABLE IF NOT EXISTS `indbandeirante`.`pass` (
  `us_ukey` INT NOT NULL COMMENT '',
  `ps_char` VARCHAR(50) NOT NULL COMMENT '',
  INDEX `fk_pass_user_idx` (`us_ukey` ASC)  COMMENT '',
  PRIMARY KEY (`us_ukey`)  COMMENT '',
  CONSTRAINT `fk_pass_user`
    FOREIGN KEY (`us_ukey`)
    REFERENCES `indbandeirante`.`user` (`us_ukey`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

/* REGISTRO PADRÃO  */
INSERT INTO USER(US_NOME,US_EMAIL,US_SEXO,US_DATA,US_TIME) VALUES ('MARCOS SOUSA','MARCOS.SOUSA0055@GMAIL.COM','M',DATE(NOW()),TIME(NOW()));
INSERT INTO PASS VALUES(LAST_INSERT_ID(),MD5('14011995'));
-- -----------------------------------------------------
-- Table `indbandeirante`.`cabeleleiros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `indbandeirante`.`cabeleleiros` ;

CREATE TABLE IF NOT EXISTS `indbandeirante`.`cabeleleiros` (
  `ca_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `xa_nome` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`ca_id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
